modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/Thiov/gulliver-fabric/issues"

[[mods]]
modId = "gulliver"
version = "${mod_version}"
displayName = "Gulliver"
displayURL = "https://github.com/Thiov/gulliver-fabric"
logoFile = "assets/gulliver/icon.png"
authors = "Thiov"
description = '''
Resize yourself or other entities from 0.125x to 8x. Movement, combat, reach, sound, and world interaction all scale with size. Inspired by UncleMion's classic Gulliver mod.
'''

[[dependencies.gulliver]]
modId = "forge"
mandatory = true
versionRange = "${loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.gulliver]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
